### ISSUE TITLE
Icon selection layout problem 

### ISSUE THREAD

**Issue by mknuts** [martinstechgarage/com.smplproducts.issues#1]
**Describe the bug
They displayed icon selection table do not display correctly 

**To Reproduce**
Edit or create an display item
Try to select an icon and you will get a layout displayed where you don’t see all icons 
I’m using iPhone 13 Pro Max running iOS 16.1, but I get the same result on my iPad (same iOS version)

**Expected behavior**
A table where I can see and select all icons 
**Screenshots**
![035A1A9A-A083-49D6-8FFC-662A2513E544](https://user-images.githubusercontent.com/23149051/199821905-55a98aed-5f84-4f62-8577-8204af7c1ad3.png)

**Desktop (please complete the following information):**
 N/A

**Smartphone (please complete the following information):**
 - Device: iPhone 13 Pro Max 
 - OS: iOS 16.1
 - Browser N/A, using Homey iOS app
 - Version 6.11.7

**Additional context**

**Comment by koktaildotcom** [comment]
Thanks @mknuts for reporting! On what build did it happen? More [...] -> Apps -> Smpl beneath logo.

**Comment by koktaildotcom** [comment]
I've reproduced the issue and it should be fixed in v2.1.4. Thank you for reporting 🙏
